name: '524-Group-19'
channels:
  - conda-forge
dependencies:
  - python=3.12.7
  - jupyterlab=4.3.1
  - altair=6.0.0
  - pyarrow=17.0.0
  - matplotlib=3.9.2
  - numpy=1.26.3
  - pandas=2.2.3
  - scikit-learn=1.5.2
  - seaborn=0.13.2
  - tabulate 0.9.0
  - click=8.1.7
  - scipy=1.13.1
  - pip=24.3.1
  - pip:
      - quarto-cli
      - vl-convert-python==1.8.0
      - vegafusion==2.0.3
      - ucimlrepo==0.0.7
      - pandera==0.20.3
      - deepchecks==0.19.1
      - pytest==7.4.4
      - Pillow==10.4.0
